load('C:\Users\Eathan\Documents\MATLAB\2012\09\PhraseBasedElementMarkovModelForAllSixBirds.mat')
load('C:\Users\Eathan\Documents\MATLAB\2012\09\ElmentStructureForAllSixBirds.mat')
%%
BaylissRandomizedPhraseMarkovModel = randomizePhraseMarkovModel(BaylissPhraseBasedElementModel);
BeasleyRandomizedPhraseMarkovModel = randomizePhraseMarkovModel(BeasleyPhraseBasedElementModel);
HT77RandomizedPhraseMarkovModel = randomizePhraseMarkovModel(HT77PhraseBasedElementModel);
HT99RandomizedPhraseMarkovModel = randomizePhraseMarkovModel(HT99PhraseBasedElementModel);
LumsdaineRandomizedPhraseMarkovModel = randomizePhraseMarkovModel(LumsdainePhraseBasedElementModel);
PowysRandomizedPhraseMarkovModel = randomizePhraseMarkovModel(PowysPhraseBasedElementModel);
%%
save 2012\09\PhraseBasedElementMarkovModelForAllSixBirds_Shuffled